import type { Metadata } from 'next'
import '@/app/globals.css'
import Header from '../../components/Header'
import Footer from '@/components/Footer/Footer'

export const metadata: Metadata = {
  title: 'GiveFlow',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='flex flex-col h-full'>
      <div className='flex-1 py-8'>
        <Header />
        <main>{children}</main>
      </div>
      <Footer />
    </div>
  )
}
