import BackButton from '@/components/BackButton'
import { Metadata } from 'next'
import React from 'react'
export const metadata: Metadata = {
  title: {
    default: 'GiveFlow',
    template: '%s - GiveFlow',
  },
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='min-h-screen relative w-[90%] mx-auto'>
      <div className='absolute left-0 top-0'>
        <BackButton />
      </div>
      <main>{children}</main>
    </div>
  )
}
