import { Metadata } from 'next'
import React from 'react'
export const metadata: Metadata = {
  title: {
    default: 'GiveFlow',
    template: '%s - GiveFlow',
  },
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <main>{children}</main>
}
