import { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import React from 'react'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    default: 'GiveFlow',
    template: '%s - GiveFlow',
  },
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        cz-shortcut-listen='true'
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <main>{children}</main>
      </body>
    </html>
  )
}
