import { Users } from '@/app/data/user'
import { ProfileSidebar } from '@/components/ProfileSideBar'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { Metadata } from 'next'
import React from 'react'
import UserProvider from './userProvider'

export const getMetadata = async ({
  params,
}: {
  params: { userId: string }
}): Promise<Metadata> => {
  const { userId } = params
  const user = Users.find(
    (user: { id: number }) => user.id === parseInt(userId)
  )

  return {
    title: {
      default: 'GiveFlow',
      template: `${user?.first_name} - GiveFlow`,
    },
    description: 'Generated by create next app',
  }
}

export default function ProfileLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SidebarProvider>
      <div className='min-h-screen flex w-full'>
        <ProfileSidebar />
        <main className='flex-1'>
          <div className='block md:hidden'>
            <SidebarTrigger />
          </div>
          <div className='w-[90%] mx-auto mt-10'>
            <UserProvider>{children}</UserProvider>
          </div>
        </main>
      </div>
    </SidebarProvider>
  )
}
