import { ProfileSidebar } from '@/components/ProfileSideBar'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { Metadata } from 'next'
import React from 'react'
export const metadata: Metadata = {
  title: {
    default: 'GiveFlow',
    template: '%s - GiveFlow',
  },
  description: 'Generated by create next app',
}

export default function ProfileLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SidebarProvider>
      <div className='min-h-screen flex w-full'>
        <ProfileSidebar />
        <main className='flex-1'>
          <div className='w-[90%] mx-auto mt-10'>{children}</div>
        </main>
      </div>
    </SidebarProvider>
  )
}
